from plotbeeStatistics import extract_flower_data
from plotbeeStatistics import extract_visit_data
from plotbeeStatistics import combine_tables
from plotbeeStatistics import validate_data
from plotbeeStatistics import display_statistics_table